### ISSUE TITLE
Verify subject.UnregisterObserver works

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/go-observing#51]
The following error indicates that something isn't quite right with `subject.UnregisterObserver()`:

```console
--- FAIL: TestInitializerImpl_UnregisterObserver (0.38s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x7ff7e96d01b2]

goroutine 24 [running]:
testing.tRunner.func1.2({0x7ff7e9a67e40, 0x7ff7e99b7d60})
	C:/hostedtoolcache/windows/go/1.21.1/x64/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.21.1/x64/src/testing/testing.go:1548 +0x397
panic({0x7ff7e9a67e40?, 0x7ff7e99b7d60?})
	C:/hostedtoolcache/windows/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
github.com/senzing/g2-sdk-go-base/g2config.(*G2config).UnregisterObserver(0xc00039a740, {0x7ff7e9c5be30, 0x7ff7ea217220}, {0x7ff7e9c58838?, 0xc000093050?})
	C:/Users/runneradmin/go/pkg/mod/github.com/senzing/g2-sdk-go-base@v0.3.0/g2config/g2config.go:651 +0x352
github.com/senzing/init-database/senzingconfig.(*SenzingConfigImpl).UnregisterObserver(0xc0002fe2d0, {0x7ff7e9c5be30, 0x7ff7ea217220}, {0x7ff7e9c58838?, 0xc000093050})
	D:/a/init-database/init-database/senzingconfig/senzingconfig.go:769 +0x4bf
github.com/senzing/init-database/initializer.(*InitializerImpl).UnregisterObserver(0xc000325ee0, {0x7ff7e9c5be30, 0x7ff7ea217220}, {0x7ff7e9c58838?, 0xc000093050})
	D:/a/init-database/init-database/initializer/initializer.go:767 +0x5e8
github.com/senzing/init-database/initializer.TestInitializerImpl_UnregisterObserver(0x0?)
	D:/a/init-database/init-database/initializer/initializer_test.go:109 +0x177
testing.tRunner(0xc00039c4e0, 0x7ff7e9ba5b38)
	C:/hostedtoolcache/windows/go/1.21.1/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	C:/hostedtoolcache/windows/go/1.21.1/x64/src/testing/testing.go:1648 +0x3ad
FAIL	github.com/senzing/init-database/initializer	2.597s
```

Currently `subject.UnregisterObserver()` isn't a well tested method call, so the issue probably affects all callers of the method.
- https://deps.dev/go/github.com%2Fsenzing%2Fgo-observing/v0.2.7/dependents

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/senzing-garage/go-observing/pull/95
